# Generated by Django 4.2.4 on 2023-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contactus_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('userid', models.CharField(max_length=200)),
                ('productid', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=200)),
                ('transactionid', models.CharField(max_length=200)),
            ],
        ),
    ]
